services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - fiipractic-sql:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  fiipractic-api:
    build:
      context: ./fiipractic
    image: fiipractic:latest
    container_name: fiipractic-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: on-failure

  weatherapp-fe:
    build:
      context: ./weatherapp
    image: weatherapp:latest
    container_name: weatherapp-fe
    ports:
      - "8080:80"
    depends_on:
      - fiipractic-api
    restart: always

volumes:
  fiipractic-sql:
